import { IconType } from "react-icons"
import { FaSquareRootVariable ,FaMap } from "react-icons/fa6"
import { TbLanguage } from "react-icons/tb";
import { LuAtom , LuDna } from "react-icons/lu";
import { GrTest } from "react-icons/gr";
import { RiGovernmentFill } from "react-icons/ri";
import { MdOutlineLeaderboard } from "react-icons/md";
import { MdOutlineHistoryEdu } from "react-icons/md";
import { GiInjustice } from "react-icons/gi";
import { TbMathFunction } from "react-icons/tb";
import { IoMdGlobe } from "react-icons/io";
interface subjects {
 id : string,
 subject: string,
 logo : IconType,
 fill: string,
 bg:string,
}
export const items = [
  "English",
  "Mathematics",
  "Biology" , 
  "Further_Mathematics", 
  "Civic_Education" , 
  "Chemistry" ,
  "Physics",
  "Computer_Science" 
]

export const ProfileSubjects:{id:string , subject:string}[] = [
  { id:"1",  subject:"English"},
  { id:"2",  subject:"Mathematics"},
  { id:"3",  subject:"Physics"},
  { id:"4",  subject:"Chemistry"},
  { id:"5",  subject:"Biology"  },
  { id:"6",  subject:"Geography"},
  { id:"7",  subject:"History"},
  { id:"8",  subject:"Economics"},
  { id:"9",  subject:"Government"},
  { id:"10", subject:"Civic"},
  { id:"11", subject:"Computer"},
  { id:"12", subject:"F/Math"},
]
export const Subjects: subjects[] = [
  { id:"1",  subject:"English",            logo: TbLanguage,          fill:"fill-blue-500",       bg:"bg-blue-100"    },
  { id:"2",  subject:"Mathematics",             logo: FaSquareRootVariable,     fill:"fill-purple-500",    bg:"bg-purple-100"  },
  { id:"3",  subject:"Physics",            logo: LuAtom,              fill:"fill-cyan-500",       bg:"bg-cyan-100"    },
  { id:"4",  subject:"Chemistry",          logo: GrTest,              fill:"fill-orange-500",     bg:"bg-orange-100"  },
  { id:"5",  subject:"Biology",            logo: LuDna,               fill:"fill-green-500",      bg:"bg-green-100"   },
  { id:"6",  subject:"Geography",          logo: FaMap,               fill:"fill-teal-500",       bg:"bg-teal-100"    },
  { id:"7",  subject:"History",            logo: MdOutlineHistoryEdu, fill:"fill-amber-500",      bg:"bg-amber-100"   },
  { id:"8",  subject:"Economics",          logo: MdOutlineLeaderboard,fill:"fill-emerald-500",    bg:"bg-emerald-100" },
  { id:"9",  subject:"Government",         logo: RiGovernmentFill,    fill:"fill-red-500",        bg:"bg-red-100"     },
  { id:"10", subject:"Civic_Education",    logo: GiInjustice,         fill:"fill-indigo-500",     bg:"bg-indigo-100"  },
  { id:"11", subject:"Computer_Science",   logo: IoMdGlobe,           fill:"fill-sky-500",        bg:"bg-sky-100"     },
  { id:"12", subject:"Further_Mathematics",logo: TbMathFunction,      fill:"fill-violet-500",     bg:"bg-violet-100"  },
]

export const subjectTopics: Record<string, { id: string; title: string; done: boolean , pdf?:string | null  , enabled:boolean}[]> = {
  Mathematics: [
  { id: "1", title: "Number Base System", done: false, enabled:true, pdf:"/pdf/Math/number-base.pdf" },
  { id: "2", title: "Algebraic Expressions", done: false, enabled:true, pdf:"/pdf/Math/algebra.pdf" },
  { id: "3", title: "Arithemetic", done: false, enabled:false, pdf:"/pdf/Math/Arithemetic.pdf" },
  { id: "4", title: "Indicies and standard form", done: false, enabled:false, pdf:"/pdf/Math/Indicies_and_Standard_Form.pdf" },
  { id: "5", title: "Logarithms", done: false, enabled:false, pdf:"/pdf/Math/Logarithms.pdf" },
  { id: "6", title: "Sets", done: false, enabled:false, pdf:"/pdf/Math/Sets.pdf" },
  { id: "7", title: "Simple Equations and Variation", done: false, enabled:false, pdf:"/pdf/Math/Simple_Equations_and_Variation.pdf" },
  { id: "8", title: "Quadratic Equations 1", done: false, enabled:false, pdf:"/pdf/Math/Quadratic_Equations_1.pdf" },
  { id: "9", title: "Logical Reasoning", done: false, enabled:false, pdf:"/pdf/Math/Logical_Reasoning.pdf" },
  { id: "10", title: "Construction", done: false, enabled:false, pdf:"/pdf/Math/Construction.pdf" },
  { id: "11", title: "Proof of some basic theorem", done: false, enabled:false, pdf:"/pdf/Math/Proof_of_Some_Basic_Theorem.pdf" },
  { id: "12", title: "Trigonometry 1", done: false, enabled:false, pdf:"/pdf/Math/Trigonometry_1.pdf" },
  { id: "13", title: "Mensuration", done: false, enabled:false, pdf:"/pdf/Math/Mensuration.pdf" },
  { id: "14", title: "Data Presentation", done: false, enabled:false, pdf:"/pdf/Math/Data_Presentation.pdf" },
  { id: "15", title: "Approximations", done: false, enabled:false, pdf:"/pdf/Math/Approximations.pdf" },
  { id: "16", title: "Sequence and Series", done: false, enabled:false, pdf:"/pdf/Math/Sequence_and_Series.pdf" },
  { id: "17", title: "Quadratic Equations 2", done: false, enabled:false, pdf:"/pdf/Math/Quadratic_Equations_2.pdf" },
  { id: "18", title: "Linear Inequalities", done: false, enabled:false, pdf:"/pdf/Math/Linear_Inequalities.pdf" },
  { id: "19", title: "Algebraic Fractions", done: false, enabled:false, pdf:"/pdf/Math/Algebraic_Fractions.pdf" },
  { id: "20", title: "Circles , Angle Properties & Cylic Quadilaterals", done: false, enabled:false, pdf:"/pdf/Math /Circles_Angle_Properties_and_Cyclic_Quadrilaterals.pdf" },
  { id: "21", title: "Intersecting Chords and Tangents", done: false, enabled:false, pdf:"/pdf/Math/Intersecting_Chords_and_Tangents.pdf" },
  { id: "22", title: "Bearing", done: false, enabled:false, pdf:"/pdf/Math/Bearing.pdf" },
  { id: "23", title: "Measures of Central Tendency", done: false, enabled:false, pdf:"/pdf/Math/Measures_of_Central_Tendency.pdf" },
  { id: "24", title: "Measures of Dispersion", done: false, enabled:false, pdf:"/pdf/Math/Measures_of_Dispersion.pdf" },
  { id: "25", title: "Cummulative Frequency Graph", done: false, enabled:false, pdf:"/pdf/Math/Cummulative_Frequency_Graph.pdf" },
  { id: "26", title: "Probability", done: false, enabled:false, pdf:"/pdf/Math/Probability.pdf" },
  { id: "27", title: "Surds", done: false, enabled:false, pdf:"/pdf/Math/Surds.pdf" },
  { id: "28", title: "Matrices and Determinants", done: false, enabled:false, pdf:"/pdf/Math/Matrices_and_Determinants.pdf" },
  { id: "29", title: "Arithemetic of Finance", done: false, enabled:false, pdf:"/pdf/Math/Arithemetic_of_Finance.pdf" },
  { id: "30", title: "Graphs of sine and cosine", done: false, enabled:false, pdf:"/pdf/Math/Graphs_of_Sine_and_Cosine.pdf" },
  { id: "31", title: "Longitude and Latitudes", done: false, enabled:false, pdf:"/pdf/Math/Longitude_and_Latitudes.pdf" },
  { id: "32", title: "Coordinate Geometry", done: false, enabled:false, pdf:"/pdf/Math/Coordinate_Geometry.pdf" },
],

English: [
  { id: "1", title: "Parts of Speech", done: false, enabled:true ,pdf:"/pdf/English/pofSpeech.pdf" },
  { id: "2", title: "Common Errors", done: false, enabled:false, pdf:"/pdf/English/Common_Errors.pdf" },
  { id: "3", title: "Articles", done: false, enabled:false, pdf:"/pdf/English/Articles.pdf" },
  { id: "4", title: "Question Tags", done: false, enabled:false, pdf:"/pdf/English/Question_Tags.pdf" },
  { id: "5", title: "Real and Unreal Future", done: false, enabled:false, pdf:"/pdf/English/Real_and_Unreal_Future.pdf" },
  { id: "6", title: "The Subjunctive", done: false, enabled:false, pdf:"/pdf/English/The_Subjunctive.pdf" },
  { id: "7", title: "Comparison and Consistency", done: false, enabled:false, pdf:"/pdf/English/Comparison_and_Consistency.pdf" },
  { id: "8", title: "Adverbial Order", done: false, enabled:false, pdf:"/pdf/English/Adverbial_Order.pdf" },
  { id: "9", title: "Group Terms", done: false, enabled:false, pdf:"/pdf/English/Group_Terms.pdf" },
  { id: "10", title: "Phrasal Verbs", done: false, enabled:false, pdf:"/pdf/English/Phrasal_Verbs.pdf" },
  { id: "11", title: "Invariable Plural Nouns", done: false, enabled:false, pdf:"/pdf/English/Invariable_Plural_Nouns.pdf" },
  { id: "12", title: "Nouns that do not Accomodate", done: false, enabled:false, pdf:"/pdf/English/Nouns_that_do_not_Accomodate.pdf" },
  { id: "13", title: "S In The Plural Form", done: false, enabled:false, pdf:"/pdf/English/S_In_The_Plural_Form.pdf" },
  { id: "14", title: "Concord", done: false, enabled:false, pdf:"/pdf/English/Concord.pdf" },
  { id: "15", title: "Active and Passive Voice", done: false, enabled:false, pdf:"/pdf/English/Active_and_Passive_Voice.pdf" },
  { id: "16", title: "Prepositions", done: false, enabled:false, pdf:"/pdf/English/Prepositions.pdf" },
  { id: "17", title: "Plural Compounds", done: false, enabled:false, pdf:"/pdf/English/Plural_Compounds.pdf" },
  { id: "18", title: "Pronouns", done: false, enabled:false, pdf:"/pdf/English/Pronouns.pdf" },
  { id: "19", title: "Irregular Verbs", done: false, enabled:false, pdf:"/pdf/English/Irregular_Verbs.pdf" },
  { id: "20", title: "Irregular Plurals", done: false, enabled:false, pdf:"/pdf/English/Irregular_Plurals.pdf" },
  { id: "21", title: "Adjectival Order", done: false, enabled:false, pdf:"/pdf/English/Adjectival_Order.pdf" },
  { id: "22", title: "Verbs without present Continous Form", done: false, enabled:false, pdf:"/pdf/English/Verbs_without_present_Continous_Form.pdf" },
  { id: "23", title: "Verbs wrongly used with a Preposition", done: false, enabled:false, pdf:"/pdf/English/Verbs_wrongly_used_with_a_Preposition.pdf" },
  { id: "24", title: "Auxiliary Verbs", done: false, enabled:false, pdf:"/pdf/English/Auxiliary_Verbs.pdf" },
  { id: "25", title: "The Apostrophe", done: false, enabled:false, pdf:"/pdf/English/The_Apostrophe.pdf" },
  { id: "26", title: "Words and Synonyms", done: false, enabled:false, pdf:"/pdf/English/Words_and_Synonyms.pdf" },
  { id: "27", title: "Words and Antonyms", done: false, enabled:false, pdf:"/pdf/English/Words_and_Antonyms.pdf" },
  { id: "28", title: "Invariable Singular Nouuns with S endings", done: false, enabled:false, pdf:"/pdf/English/Invariable_Singular_Nouuns_with_S_endings.pdf" },
  { id: "29", title: "Direct and Indirect Speech", done: false, enabled:false, pdf:"/pdf/English/Direct_and_Indirect_Speech.pdf" },
  { id: "30", title: "Words that go in Pairs", done: false, enabled:false, pdf:"/pdf/English/Words_that_go_in_Pairs.pdf" },
  { id: "31", title: "The Gerund", done: false, enabled:false, pdf:"/pdf/English/The_Gerund.pdf" },
  { id: "32", title: "Contractions", done: false, enabled:false, pdf:"/pdf/English/Contractions.pdf" },
  { id: "33", title: "Punctuation Marks", done: false, enabled:false, pdf:"/pdf/English/Punctuation_Marks.pdf" },
  { id: "34", title: "Letters and Essays", done: false, enabled:false, pdf:"/pdf/English/Letters_and_Essays.pdf" },
  { id: "35", title: "Comprehension (SSCE-WAEC & NECO)", done: false, enabled:false, pdf:"/pdf/English/Comprehension_SSCE_WAEC_NECO.pdf" },
  { id: "36", title: "Summary", done: false, enabled:false, pdf:"/pdf/English/Summary.pdf" },
  { id: "37", title: "Comprehension(UTME)", done: false, enabled:false, pdf:"/pdf/English/Comprehension_UTME.pdf" },
  { id: "38", title: "Idioms", done: false, enabled:false, pdf:"/pdf/English/Idioms.pdf" },
  { id: "39", title: "Spellings", done: false, enabled:false, pdf:"/pdf/English/Spellings.pdf" },
  { id: "40", title: "Register", done: false, enabled:false, pdf:"/pdf/English/Register.pdf" },
  { id: "41", title: "Oral English", done: false, enabled:false, pdf:"/pdf/English/Oral_English.pdf" },
  { id: "42", title: "Sentence Detachment", done: false, enabled:false, pdf:"/pdf/English/Sentence_Detachment.pdf" },
  { id: "43", title: "Distinctive Sounds", done: false, enabled:false, pdf:"/pdf/English/Distinctive_Sounds.pdf" },
  { id: "44", title: "Tautology", done: false, enabled:false, pdf:"/pdf/English/Tautology.pdf" },
],



Physics: [
  { id: "1", title: "Measurements & units", done: true, enabled:true, pdf:"/pdf/Physics/measure.pdf" },
  { id: "2", title: "Scaler and Vector Quantities", done: false, enabled:true, pdf:"/pdf/Physics/Waves_and_Sound.pdf" },
  { id: "3", title: "Motion", done: false, enabled:false, pdf:"/pdf/Physics/Electricity.pdf" },
  { id: "4", title: "Equilibruim of forces", done: false, enabled:false, pdf:"/pdf/Physics/Electromagnetism.pdf" },
  { id: "5", title: "Friction", done: false, enabled:false, pdf:"/pdf/Physics/Electromagnetism.pdf" },
  { id: "6", title: "Simple Machine", done: false, enabled:false, pdf:"/pdf/Physics/Modern_Physics.pdf" },
  { id: "7", title: "Elasticity", done: false, enabled:false, pdf:"/pdf/Physics/Modern_Physics.pdf" },
  { id: "8", title: "Work , energy and Power", done: false, enabled:false, pdf:"/pdf/Physics/Modern_Physics.pdf" },
  { id: "9", title: "Heat Energy", done: false, enabled:false, pdf:"/pdf/Physics/Modern_Physics.pdf" },
  { id: "10", title: "Thermal Expansion", done: false, enabled:false, pdf:"/pdf/Physics/Modern_Physics.pdf" },
  { id: "11", title: "Electrostatics", done: false, enabled:false, pdf:"/pdf/Physics/Modern_Physics.pdf" },
  { id: "12", title: "Current Electricity", done: false, enabled:false, pdf:"/pdf/Physics/Modern_Physics.pdf" },
  { id: "13", title: "Electrical Energy and Power", done: false, enabled:false, pdf:"/pdf/Physics/Modern_Physics.pdf" },
  { id: "14", title: "Particulate Nature of matter", done: false, enabled:false, pdf:"/pdf/Physics/Modern_Physics.pdf" },
  { id: "15", title: "Fluids at rest and in motion", done: false, enabled:false, pdf:"/pdf/Physics/Modern_Physics.pdf" },
  { id: "16", title: "Heat transfer", done: false, enabled:false, pdf:"/pdf/Physics/Modern_Physics.pdf" },
  { id: "17", title: "Equilibruim of bodies in liquid", done: false, enabled:false, pdf:"/pdf/Physics/Modern_Physics.pdf" },
  { id: "18", title: "Temperature and it's measurement", done: false, enabled:false, pdf:"/pdf/Physics/Modern_Physics.pdf" },
  { id: "19", title: "Heat capacity and specific heat capacity", done: false, enabled:false, pdf:"/pdf/Physics/Modern_Physics.pdf" },
  { id: "20", title: "Change of state", done: false, enabled:false, pdf:"/pdf/Physics/Modern_Physics.pdf" },
  { id: "21", title: "Vapours", done: false, enabled:false, pdf:"/pdf/Physics/Modern_Physics.pdf" },
  { id: "22", title: "Gas laws", done: false, enabled:false, pdf:"/pdf/Physics/Modern_Physics.pdf" },
  { id: "23", title: "Waves", done: false, enabled:false, pdf:"/pdf/Physics/Modern_Physics.pdf" },
  { id: "24", title: "Propagation of Sound Waves", done: false, enabled:false, pdf:"/pdf/Physics/Modern_Physics.pdf" },
  { id: "25", title: "Characteristics of sound waves", done: false, enabled:false, pdf:"/pdf/Physics/Modern_Physics.pdf" },
  { id: "26", title: "Light waves", done: false, enabled:false, pdf:"/pdf/Physics/Modern_Physics.pdf" },
  { id: "27", title: "Reflection of light", done: false, enabled:false, pdf:"/pdf/Physics/Modern_Physics.pdf" },
  { id: "28", title: "Refraction of light", done: false, enabled:false, pdf:"/pdf/Physics/Modern_Physics.pdf" },
  { id: "29", title: "Dispersion of light and colour", done: false, enabled:false, pdf:"/pdf/Physics/Modern_Physics.pdf" },
  { id: "30", title: "Application of light waves", done: false, enabled:false, pdf:"/pdf/Physics/Modern_Physics.pdf" },
  { id: "31", title: "Electromagnetic spectrum", done: false, enabled:false, pdf:"/pdf/Physics/Modern_Physics.pdf" },
  { id: "32", title: "Pressure", done: false, enabled:false, pdf:"/pdf/Physics/Modern_Physics.pdf" },
  { id: "33", title: "Gravitational field", done: false, enabled:false, pdf:"/pdf/Physics/Modern_Physics.pdf" },
  { id: "34", title: "Electric Cell", done: false, enabled:false, pdf:"/pdf/Physics/Modern_Physics.pdf" },
  { id: "35", title: "Galvanometer conversions", done: false, enabled:false, pdf:"/pdf/Physics/Modern_Physics.pdf" },
  { id: "36", title: "Power Transmission,wiring and fuse", done: false, enabled:false, pdf:"/pdf/Physics/Modern_Physics.pdf" },
  { id: "37", title: "Electric field and potential", done: false, enabled:false, pdf:"/pdf/Physics/Modern_Physics.pdf" },
  { id: "38", title: "Capacitors", done: false, enabled:false, pdf:"/pdf/Physics/Modern_Physics.pdf" },
  { id: "39", title: "Magnets and Magnetic fields", done: false, enabled:false, pdf:"/pdf/Physics/Modern_Physics.pdf" },
  { id: "40", title: "Electromagnetic Induction", done: false, enabled:false, pdf:"/pdf/Physics/Modern_Physics.pdf" },
  { id: "41", title: "Simple AC circuits", done: false, enabled:false, pdf:"/pdf/Physics/Modern_Physics.pdf" },
  { id: "42", title: "Conduction of Electricity", done: false, enabled:false, pdf:"/pdf/Physics/Modern_Physics.pdf" },
  { id: "43", title: "Elementary modern physics", done: false, enabled:false, pdf:"/pdf/Physics/Modern_Physics.pdf" },
  { id: "44", title: "Introductory Electronics", done: false, enabled:false, pdf:"/pdf/Physics/Modern_Physics.pdf" },
],

Chemistry: [
  { id: "1", title: "Chemical Industry", done: true, enabled:true,pdf:"/pdf/Chemistry/industry.pdf" },
  { id: "2", title: "Particulate Nature of Matter", done: false, enabled:true, pdf:"/pdf/Chemistry/Particulate_Nature_of_Matter.pdf" },
  { id: "3", title: "Separation of Mixtures", done: false, enabled:true, pdf:"/pdf/Chemistry/Separation_of_Mixtures.pdf" },
  { id: "4", title: "Chemical Combinations", done: false, enabled:true, pdf:"/pdf/Chemistry/Chemical_Combinations.pdf" },
  { id: "5", title: "State of matter & Kinetic theory of matter", done: false, enabled:true, pdf:"/pdf/Chemistry/State_of_Matter_and_Kinetic_Theory.pdf" },
  { id: "6", title: "Gas laws", done: false, enabled:true, pdf:"/pdf/Chemistry/Gas_Laws.pdf" },
  { id: "7", title: "Stoichometry", done: false, enabled:true, pdf:"/pdf/Chemistry/Stoichometry.pdf" },
  { id: "8", title: "Acid, Bases and Salts", done: false, enabled:true, pdf:"/pdf/Chemistry/Acids_Bases_and_Salts.pdf" },
  { id: "9", title: "Solubility", done: false, enabled:true, pdf:"/pdf/Chemistry/Solubility.pdf" },
  { id: "10", title: "The Periodic Table", done: false, enabled:true, pdf:"/pdf/Chemistry/The_Periodic_Table.pdf" },
  { id: "11", title: "Electronic Configurations", done: false, enabled:true, pdf:"/pdf/Chemistry/Electronic_Configurations.pdf" },
  { id: "12", title: "Air", done: false, enabled:true, pdf:"/pdf/Chemistry/Air.pdf" },
  { id: "13", title: "Water", done: false, enabled:true, pdf:"/pdf/Chemistry/Water.pdf" },
  { id: "14", title: "Environmental Pollution", done: false, enabled:true, pdf:"/pdf/Chemistry/Environmental_Pollution.pdf" },
  { id: "15", title: "Oxidation and Reduction", done: false, enabled:true, pdf:"/pdf/Chemistry/Oxidation_and_Reduction.pdf" },
  { id: "16", title: "Electrolysis", done: false, enabled:true, pdf:"/pdf/Chemistry/Electrolysis.pdf" },
  { id: "17", title: "Chemical Reactions", done: false, enabled:true, pdf:"/pdf/Chemistry/Chemical_Reactions.pdf" },
  { id: "18", title: "Chemical Equilibrium", done: false, enabled:true, pdf:"/pdf/Chemistry/Chemical_Equilibrium.pdf" },
  { id: "19", title: "Non metals and their compounds", done: false, enabled:true, pdf:"/pdf/Chemistry/Non_Metals_and_Their_Compounds.pdf" },
  { id: "20", title: "Hydrocarbons", done: false, enabled:true, pdf:"/pdf/Chemistry/Hydrocarbons.pdf" },
  { id: "21", title: "Amines", done: false, enabled:true, pdf:"/pdf/Chemistry/Amines.pdf" },
  { id: "22", title: "Carbohydrates", done: false, enabled:true, pdf:"/pdf/Chemistry/Carbohydrates.pdf" },
  { id: "23", title: "Petroleum", done: false, enabled:true, pdf:"/pdf/Chemistry/Petroleum.pdf" },
  { id: "24", title: "Nuclear Chemistry", done: false, enabled:true, pdf:"/pdf/Chemistry/Nuclear_Chemistry.pdf" },
  { id: "25", title: "Acid/Base Titrations", done: false, enabled:true, pdf:"/pdf/Chemistry/Acid_Base_Titrations.pdf" },
  { id: "26", title: "pH and pOH scale", done: false, enabled:true, pdf:"/pdf/Chemistry/pH_and_pOH_Scale.pdf" },
  { id: "27", title: "Metals and thier compounds", done: false, enabled:true, pdf:"/pdf/Chemistry/Metals_and_Their_Compounds.pdf" },
],
Biology: [
  { id: "1", title: "Introduction to Biology", done: false, enabled:true ,pdf:"/pdf/Biology/concept.pdf" },
  { id: "2", title: "Genetics", done: false, enabled:true, pdf:"/pdf/Biology/Genetics.pdf" },
  { id: "3", title: "Ecology", done: false, enabled:true, pdf:"/pdf/Biology/Ecology.pdf" },
  { id: "4", title: "Human Physiology", done: false, enabled:true, pdf:"/pdf/Biology/Human_Physiology.pdf" },
  { id: "5", title: "Evolution", done: false, enabled:true, pdf:"/pdf/Biology/Evolution.pdf" },
],

Geography: [
  { id: "1", title: "Introduction to Geography", done: false, enabled:true, pdf:"/pdf/Geography/intro.pdf" },
  { id: "2", title: "Climate & Weather", done: false, enabled:true, pdf:"/pdf/Geography/Climate_and_Weather.pdf" },
  { id: "3", title: "Population", done: false, enabled:true, pdf:"/pdf/Geography/Population.pdf" },
  { id: "4", title: "Settlement", done: false, enabled:true, pdf:"/pdf/Geography/Settlement.pdf" },
  { id: "5", title: "Environmental Resources", done: false, enabled:true, pdf:"/pdf/Geography/Environmental_Resources.pdf" },
],

History: [
  { id: "1", title: "Pre-Colonial Nigeria", done: false, enabled:true, pdf:"/pdf/History/Pre_Colonial_Nigeria.pdf" },
  { id: "2", title: "Colonial Rule", done: false, enabled:true, pdf:"/pdf/History/Colonial_Rule.pdf" },
  { id: "3", title: "Nationalism", done: false, enabled:true, pdf:"/pdf/History/Nationalism.pdf" },
  { id: "4", title: "Nigerian Independence", done: false, enabled:true, pdf:"/pdf/History/Nigerian_Independence.pdf" },
  { id: "5", title: "Military Rule in Nigeria", done: false, enabled:true, pdf:"/pdf/History/Military_Rule.pdf" },
],

Economics: [
  { id: "1", title: "Basic Economic Problems", done: false, enabled:true, pdf:"/pdf/Economics/Basic_Economic_Problems.pdf" },
  { id: "2", title: "Demand & Supply", done: false, enabled:true, pdf:"/pdf/Economics/Demand_and_Supply.pdf" },
  { id: "3", title: "Production", done: false, enabled:true, pdf:"/pdf/Economics/Production.pdf" },
  { id: "4", title: "Money & Inflation", done: false, enabled:true, pdf:"/pdf/Economics/Money_and_Inflation.pdf" },
  { id: "5", title: "International Trade", done: false, enabled:true, pdf:"/pdf/Economics/International_Trade.pdf" },
],

Government: [
  { id: "1", title: "Meaning of Government", done: false, enabled:true, pdf:"/pdf/Government/Meaning_of_Government.pdf" },
  { id: "2", title: "Constitution", done: false, enabled:true, pdf:"/pdf/Government/Constitution.pdf" },
  { id: "3", title: "Arms of Government", done: false, enabled:true, pdf:"/pdf/Government/Arms_of_Government.pdf" },
  { id: "4", title: "Democracy", done: false, enabled:true, pdf:"/pdf/Government/Democracy.pdf" },
  { id: "5", title: "Electoral Process", done: false, enabled:true, pdf:"/pdf/Government/Electoral_Process.pdf" },
],

Civic_Education: [
  { id: "1", title: "Citizenship", done: false, enabled:true, pdf:"/pdf/Civic_Education/Citizenship.pdf" },
  { id: "2", title: "Human Rights", done: false, enabled:true, pdf:"/pdf/Civic_Education/Human_Rights.pdf" },
  { id: "3", title: "Rule of Law", done: false, enabled:true, pdf:"/pdf/Civic_Education/Rule_of_Law.pdf" },
  { id: "4", title: "Democracy & Nationalism", done: false, enabled:true, pdf:"/pdf/Civic_Education/Democracy_and_Nationalism.pdf" },
  { id: "5", title: "Responsible Parenthood", done: false, enabled:true, pdf:"/pdf/Civic_Education/Responsible_Parenthood.pdf" },
],

Computer_Science: [
  { id: "1", title: "Introduction to Computers", done: false, enabled:true, pdf:"/pdf/Computer_Science/Introduction_to_Computers.pdf" },
  { id: "2", title: "Computer Hardware", done: false, enabled:true, pdf:"/pdf/Computer_Science/Computer_Hardware.pdf" },
  { id: "3", title: "Software Systems", done: false, enabled:true, pdf:"/pdf/Computer_Science/Software_Systems.pdf" },
  { id: "4", title: "Programming Basics", done: false, enabled:true, pdf:"/pdf/Computer_Science/Programming_Basics.pdf" },
  { id: "5", title: "Networking & Internet", done: false, enabled:true, pdf:"/pdf/Computer_Science/Networking_and_Internet.pdf" },
],

Further_Mathematics: [
  { id: "1", title: "Sets", done: false, enabled:true, pdf:"/pdf/Further_Mathematics/Sets.pdf" },
  { id: "2", title: "Binary Operations", done: false, enabled:true, pdf:"/pdf/Further_Mathematics/Binary_Operations.pdf" },
  { id: "3", title: "Surds", done: false, enabled:true, pdf:"/pdf/Further_Mathematics/Surds.pdf" },
  { id: "4", title: "Rational Functions", done: false, enabled:true, pdf:"/pdf/Further_Mathematics/Rational_Functions.pdf" },
  { id: "6", title: "Logical Reasoning", done: false, enabled:true, pdf:"/pdf/Further_Mathematics/Logical_Reasoning.pdf" },
  { id: "7", title: "Sequence & Series", done: false, enabled:true, pdf:"/pdf/Further_Mathematics/Sequence_and_Series.pdf" },
  { id: "8", title: "Co-ordinate Geometry", done: false, enabled:true, pdf:"/pdf/Further_Mathematics/Coordinate_Geometry.pdf" },
  { id: "9", title: "Functions", done: false, enabled:true, pdf:"/pdf/Further_Mathematics/Functions.pdf" },
  { id: "10", title: "Polynomial Functions", done: false, enabled:true, pdf:"/pdf/Further_Mathematics/Polynomial_Functions.pdf" },
  { id: "11", title: "Trigonometric Functions", done: false, enabled:true, pdf:"/pdf/Further_Mathematics/Trigonometric_Functions.pdf" },
  { id: "12", title: "Statistics", done: false, enabled:true, pdf:"/pdf/Further_Mathematics/Statistics.pdf" },
  { id: "13", title: "Permutation & Combination", done: false, enabled:true, pdf:"/pdf/Further_Mathematics/Permutation_and_Combination.pdf" },
  { id: "14", title: "Dynamics", done: false, enabled:true, pdf:"/pdf/Further_Mathematics/Dynamics.pdf" },
  { id: "15", title: "Binomial Theorem", done: false, enabled:true, pdf:"/pdf/Further_Mathematics/Binomial_Theorem.pdf" },
  { id: "16", title: "Diffrentiation", done: false, enabled:true, pdf:"/pdf/Further_Mathematics/Differentiation.pdf" },
  { id: "17", title: "Vectors", done: false, enabled:true, pdf:"/pdf/Further_Mathematics/Vectors.pdf" },
  { id: "18", title: "Matrices and Linear Transformations", done: false, enabled:true, pdf:"/pdf/Further_Mathematics/Matrices_and_Linear_Transformations.pdf" },
  { id: "19", title: "Integration", done: false, enabled:true, pdf:"/pdf/Further_Mathematics/Integration.pdf" },
  { id: "20", title: "Probability", done: false, enabled:false, pdf:"/pdf/Further_Mathematics/Probability.pdf" },
  { id: "21", title: "Statics", done: false, enabled:false, pdf:"/pdf/Further_Mathematics/Statics.pdf" },
],
}